import { createSlice } from "@reduxjs/toolkit";

// Redux Slice: CartSlice
// A Redux Slice combines reducer logic and actions in a single file using Redux Toolkit's createSlice
// The slice manages the shopping cart state and all operations related to cart items
export const CartSlice = createSlice({
  name: "cart", // Name of the slice - used as the key in Redux store
  // Initial State: The default state of the cart
  initialState: {
    items: [], // Initialize items as an empty array
  },
  // Reducers: Pure functions that respond to actions and update the state
  // Redux Toolkit uses Immer library, allowing us to "mutate" state directly (it's handled internally)
  reducers: {
    // ACTION: addItem - Adds a new product to cart or increments quantity if it already exists
    // action.payload contains the plant object passed from the component
    addItem: (state, action) => {
      const newItem = action.payload;
      // Check if item already exists in cart by name
      const itemExists = state.items.find((item) => item.name === newItem.name);

      if (itemExists) {
        // If item exists, increase its quantity (prevents duplicate items)
        itemExists.quantity = (itemExists.quantity || 1) + 1;
      } else {
        // If item doesn't exist, add it to the cart with quantity 1
        state.items.push({
          name: newItem.name,
          image: newItem.image,
          cost: newItem.cost,
          quantity: 1,
        });
      }
    },
    // ACTION: removeItem - Removes a product from the cart
    // action.payload contains the item name to remove
    removeItem: (state, action) => {
      const itemNameToRemove = action.payload;
      // Filter out the item with the specified name from the cart
      state.items = state.items.filter(
        (item) => item.name !== itemNameToRemove,
      );
    },
    // ACTION: updateQuantity - Updates the quantity of an existing cart item
    // action.payload contains {itemName, quantity}
    updateQuantity: (state, action) => {
      const { itemName, quantity } = action.payload;
      // Find the item and update its quantity
      const itemToUpdate = state.items.find((item) => item.name === itemName);
      if (itemToUpdate) {
        itemToUpdate.quantity = quantity; // Update the quantity of the specified item in the cart
      }
    },
  },
});

// Export Actions: These are automatically generated by Redux Toolkit's createSlice
// Actions are dispatched from components to trigger reducer functions
export const { addItem, removeItem, updateQuantity } = CartSlice.actions;

// Export Reducer: This is the root reducer for the cart slice
// It's used when configuring the Redux store
export default CartSlice.reducer;
